generate_test = """        WHEN("The script \\"v = sfoav.getOption(\\"meshes\\");\\"")
        {
            console.runString("v = sfoav.getOption(\\"meshes\\");");
            THEN("v is DEFAULT")
            {
                REQUIRE(console.getGlobal<TYPE>("v").MEMBER == DEFAULT);
            }
            WHEN("The script \\"sfoav.setOption(\\"meshes\\", SET); v = sfoav.getOption(\\"meshes\\");\\"")
            {
                console.runString("sfoav.setOption(\\"meshes\\", SET); v = sfoav.getOption(\\"meshes\\");");
                THEN("v is SET")
                {
                    CONDITION
                }
            }
        }
"""

tests = """/*
    Tests are generated by tests/generate_lua_options_interop_tests.py
*/
SCENARIO("Lua options interop")
{
    jLog::Log l;
    GIVEN(\"A Lua console with default CommandLine values\")
    {
        Console console(l, &vs, &options, &camera);

"""

for option in ["meshes", "hideAtoms", "showAxes", "showCell",
             "hideInfoText", "play", "noCentering", "darkTheme",
             "noTransparencySorting", "sizeByMass"]:
    test = generate_test
    for (k, v) in [("meshes", option), ("DEFAULT", "false"),
                   ("SET", "true"), ("TYPE", "LuaBool"),
                   ("MEMBER", "bit"),
                   ("CONDITION", "REQUIRE(console.getGlobal<LuaBool>(\"v\").bit == true);")]:
        test = test.replace(k, v)
    tests += test+"\n"

for (option, default) in [("levelOfDetail", 0), ("msaa", 0),
                          ("speed", 60), ("bondCutOff", 0),
                          ("bondSize", 1), ("atomSize", 1),
                          ("globalAtomAlpha", 1), ("globalBondAlpha", 1),
                          ("deemphasisAlpha", 0.25)]:
    test = generate_test
    for (k, v) in [("meshes", option), ("DEFAULT", str(default)),
                   ("SET", "31"), ("TYPE", "LuaNumber"),
                   ("MEMBER", "n"),
                   ("CONDITION", "REQUIRE_THAT(console.getGlobal<LuaNumber>(\"v\").n, WithinAbs(31, tol));")]:
        test = test.replace(k, v)
    tests += test+"\n"

tests += "        #ifdef WITH_FFMPEG\n"
for (option, default) in [("preset", "slow"), ("codec", "libx264"),
                          ("profile", "main")]:
    test = generate_test
    for (k, v) in [("meshes", option), ("DEFAULT", str(default)),
                   ("SET", "TEST"), ("TYPE", "LuaString"),
                   ("MEMBER", "characters"),
                   ("CONDITION", "REQUIRE(\"TEST\" == console.getGlobal<LuaString>(\"v\").characters);")]:
        test = test.replace(k, v)
    tests += test
tests += "        #endif\n"
tests += """    }
}"""
print(tests)